// CounterSlice.js
import { createSlice } from '@reduxjs/toolkit';

// Create a slice of the Redux state
const CounterSlice = createSlice({
  name: 'counter',
  initialState: { count: 0 },
  reducers: {
    increment: (state) => {
      state.count += 1; // Mutate the state directly (Immer.js handles immutability)
    },
    decrement: (state) => {
      state.count -= 1;
    },
  },
});

// Export actions generated by createSlice
export const { increment, decrement } = CounterSlice.actions;

// Export the reducer to be used in the store
export default CounterSlice.reducer;
